# Generated by Django 5.1.1 on 2024-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_companies_user_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='avatars/', width_field=200),
        ),
    ]
